---
title: "5.1_read_data_from_web"
author: "Wenshan Qu (wq2160)"
date: "10/19/2021"
output: html_document
---

```{r}
library(tidyverse)
library(rvest)
library(httr)


knitr::opts_chunk$set(
  fig.width = 6,
  fig.asp = .6,
  out.width = "90%"
)

theme_set(theme_minimal() + theme(legend.position = "bottom"))

options(
  ggplot2.continuous.colour = "viridis",
  ggplot2.continuous.fill = "viridis"
)

scale_colour_discrete = scale_colour_viridis_d
scale_fill_discrete = scale_fill_viridis_d
```

## NSDUH data

```{r}
url = "http://samhda.s3-us-gov-west-1.amazonaws.com/s3fs-public/field-uploads/2k15StateFiles/NSDUHsaeShortTermCHG2015.htm"

drug_use_html = 
  read_html(url)

drug_use_df = 
  drug_use_html %>% 
  html_table() %>%  ## 15 tables
  first() %>% ## Give me the first table
  slice(-1)
```

## Star wars

```{r}
sw_url = "https://www.imdb.com/list/ls070150896/"

sw_html = 
  read_html(sw_url)

title_vec = 
  sw_html %>%
  html_elements(".lister-item-header a") %>%
  html_text()

gross_rev_vec = 
  sw_html %>%
  html_elements(".text-small:nth-child(7) span:nth-child(5)") %>%
  html_text()

runtime_vec = 
  sw_html %>%
  html_elements(".runtime") %>%
  html_text()

sw_df = 
  tibble(
    title = title_vec,
    rev = gross_rev_vec,
    runtime = runtime_vec)
```


## Dynamite reviews

```{r}
url = "https://www.amazon.com/product-reviews/B00005JNBQ/ref=cm_cr_arp_d_viewopt_rvwer?ie=UTF8&reviewerType=avp_only_reviews&sortBy=recent&pageNumber=1"

dynamite_html = read_html(url)

review_titles = 
  dynamite_html %>%
  html_elements(".a-text-bold span") %>%
  html_text()

review_stars = 
  dynamite_html %>%
  html_elements("#cm_cr-review_list .review-rating") %>%
  html_text()

review_text = 
  dynamite_html %>%
  html_elements(".review-text-content span") %>%
  html_text()

reviews = tibble(
  title = review_titles,
  stars = review_stars,
  text = review_text
)

```


## Try some APIs

Get some data from API about water.

```{r}
water_df = 
  GET("https://data.cityofnewyork.us/resource/ia2d-e54m.csv") %>% 
  content()
```

Let's look at JSON!

```{r}
water_df = 
  GET("https://data.cityofnewyork.us/resource/ia2d-e54m.json") %>% 
  content("text") %>% 
  jsonlite::fromJSON() %>% 
  as_tibble()
```

We use JSON bcs sometimes the data is complicated and could not be simply stored in a csv file.

Another case:

BRFSS data via API
```{r}
brfss_df = 
  GET("https://chronicdata.cdc.gov/resource/acme-vg9e.csv",
      query = list("$limit" = 5000)) %>%  ## By default, the CDC API limits data to the first 1000 rows.
  content()
```

Pokemon API

```{r}
poke_data = 
  GET("https://pokeapi.co/api/v2/pokemon/1") %>% 
  content()

poke_data[["name"]]
poke_data[["height"]]
poke_data[["abilities"]]
```

